exclude: [
  'node_modules/**',
  '_src/style/vendor/**'
]

linters:
  Indentation:
    enabled: false
  ZeroUnit:
    enabled: false
  LeadingZero:
    enabled: false
  PropertySortOrder:
    enabled: false
  NestingDepth:
    enabled: false
  SelectorDepth:
    enabled: false
  UnnecessaryParentReference:
    enabled: false
  IdSelector:
    enabled: false
  SelectorFormat:
    enabled: false
  SpaceAfterComma:
    enabled: false
  MergeableSelector:
    enabled: false
  QualifyingElement:
    enabled: false
